name: repair-app

services:
  builder:
    build: .
    volumes:
      - jars:/artifact

  # Инфраструктура: Брокер сообщений
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Инфраструктура: Трассировка
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  # Инфраструктура: Метрики
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - microservices-net

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  # Микросервисы
  analytics-service:
    build: ./service/analytic
    ports:
      - "9091:9090" # gRPC порт
    volumes:
      - jars:/artifact
    working_dir: /artifact
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      builder:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  notification-service:
    build: ./service/notification
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8083
    volumes:
      - jars:/artifact
    working_dir: /artifact
    depends_on:
      builder:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  audit-service:
    build: ./service/audit
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8082
    volumes:
      - jars:/artifact
    working_dir: /artifact
    depends_on:
      builder:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  demo-rest:
    build: ./service/main
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      # Указываем адрес gRPC сервиса внутри сети Docker
      - GRPC_CLIENT_ANALYTICS_SERVICE_ADDRESS=static://analytics-service:9090
    volumes:
      - jars:/artifact
    working_dir: /artifact
    depends_on:
      builder:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      analytics-service:
        condition: service_started
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  jars:
